% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={resevol: an R package for spatially explicit models of pesticide resistance given evolving pest genomes},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[R]{RESEVOL, AN R PACKAGE}
\usepackage{lineno}
\linenumbers
\modulolinenumbers[2]
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{acm}

\title{resevol: an R package for spatially explicit models of pesticide resistance given evolving pest genomes}
\author{A. Bradley Duthie\(^{1,*}\), Rosie Mangan\(^{1}\), C. Rose McKeon\(^{1}\),\\
Matthew C. Tinsley\(^{1}\), and Luc F. Bussière\(^{2,3}\)}
\date{{[}1{]} Biological and Environmental Sciences, University of Stirling, Stirling, UK {[}2{]}Biological and Environmental Sciences, University of Gothenburg, Gothenburg, Sweden {[}3{]} Gothenburgh Global Biodiversity Centre, Gothenburg, Sweden {[}*{]} \href{mailto:alexander.duthie@stir.ac.uk}{\nolinkurl{alexander.duthie@stir.ac.uk}}}

\begin{document}
\maketitle

\setstretch{2}
\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{abstract}{%
\section*{Abstract}\label{abstract}}
\addcontentsline{toc}{section}{Abstract}

The evolution of pesticide resistance is a widespread problem with potentially severe consequences for global food security.
We introduce the resevol R package, which simulates individual-based models of pests with evolving genomes that produce complex, polygenic, and covarying traits affecting pest life history and pesticide resistance.
Simulations are modelled on a spatially-explicit and highly customisable landscape in which crop and pesticide application and rotation can vary, making the package a highly flexible tool for both general and tactical models of pest management and resistance evolution.
We present the key features of the resevol package and demonstrate its use for a simple example simulating pests with two covarying traits.
The resevol R package is open source under GNU Public License. All source code and documentation are available on GitHub.

\textbf{Key words:} \emph{pest management}, \emph{food security}, \emph{ecological modelling}, \emph{pesticide}, \emph{resistance evolution}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Insect resistance to pesticides is a wicked and widespread problem \citep{Gould2018}.
Predicting, identifying, and ultimately delaying the evolution of insecticide resistance is therefore critical for ensuring sustainable global food security \citep{Hawkins2019, Lykogianni2021}.
To manage pesticide resistance, various strategies have been proposed to disrupt or weaken selection.
These strategies often focus on varying the location and timing of pesticide application, and therefore varying the strength of selection for pesticide resistance, so that pest susceptibility to one or more pesticides is maintained \citep{Ives2002, Liang2013, Carriere2016, Liang2018, South2018, Sudo2018, Saikai2021}.
Pesticide resistance management has mostly been associated with the effect of single genes.
In such cases, resistance alleles have binary effects on phenotype, enabling resistant phenotypes to arise from genetic changes at single or a small number of loci \citep{Raymond2001, Ffrench-Constant2004, Ffrench-Constant2013}.
Nevertheless, resistance attributable to polygenic effects is also well-established \citep{Via1986, Firko1990, Busi2013, Haridas2018, Green2020, Mangan2023}.
And the relevance of polygenic resistance is likely to further increase given a rising interest in biological controls for sustainable crop protection \citep[e.g.,][]{Green2020, Elnahal2022, Mangan2023}.
Developing strategies to maximise the efficacy of these tools is critical, and such strategies should be well-informed by predictions made from detailed, quantitative genetic models.
Here we introduce the resevol R package as a tool for building individual-based models and simulating pest management \citep{Daly2022}.

The resevol package applies individual-based modelling and a quantitative genetics approach to simulate the evolution of a pest population on a changing landscape.
Multiple traits determine the overall fitness of any pest genotype.
For example, while alleles conferring resistance to a particular pesticide enhance fitness in the presence of that pesticide, they could also impose reproductive fitness costs.
Such trade-offs can be quantified by the genetic covariance between traits.
A focal goal of the resevol package is to model traits with a pre-specified, but potentially evolving, genetic covariance structure.
To achieve this goal, each individual has a genome with \(L\) loci that underlie a set of \(T\) potentially evolving traits.
Pleiotropic loci can vary in their effects on the direction and magnitude of polygenic traits, causing population-wide trait covariance to arise mechanistically from the underlying genetic architecture of individuals.
To achieve this, two separate steps are necessary.
First, an evolutionary algorithm is used to find a network of internal nodes that map standard random normal loci values to covarying traits.
Values used to map loci to traits are incorporated into individual genomes.
Second, a population of asexual or sexual individuals is initialised and simulated on a spatially explicit landscape separated into distinct units (e.g., farms).
Land units can apply one of up to 10 pesticides, and one of up to 10 landscape types at a given time (for simplicity, here we interpret landscape types to be crop types).
Pesticides and crops rotate independently within farms over time in a pre-specified way.
The resevol package can thereby model complex and evolving agricultural pest traits over realistic landscapes that undergo different pesticide use and crop regimes.

\hypertarget{design-and-implementation}{%
\section{Design and Implementation}\label{design-and-implementation}}

\hypertarget{mine_gmatrix}{%
\subsection{Covarying pest quantitative traits}\label{mine_gmatrix}}

The first step of simulation is building individual genomes.
This step is separate because it is computationally intensive, and genomes that are built might need to be inspected and stored.
High computation time is due to the mechanistic nature of how genomes and covarying traits are modelled.
Instead of imposing a trait covariance structure directly, an evolutionary algorithm is used to find a network that maps standard random normal values (loci) to covarying values (traits).
This is useful because it allows genomes to model potentially evolving physiological constraints, and trade-offs among traits, from the bottom up.
Since multiple networks can potentially map loci to the same trait covariance structure, it is possible to replicate evolution with different randomly generated genetic architectures.
This approach to modelling individual genomes and traits thereby increases the complexity of questions that can be addressed for simulating evolution in agricultural pests.

\begin{figure}
\centering
\includegraphics{ms_files/figure-latex/network-1.pdf}
\caption{\label{fig:network}Example network mapping loci (green circles) to traits (red diamonds) through an intermediate set of hidden layers (blue squares) in the \texttt{mine\_gmatrix} function. Individual genomes in the resevol R package consist of standard random normal values for loci, real values for black arrows linking nodes, and real values for traits. Values shown for loci and arrows are an example for illustration.}
\end{figure}

Conceptually, the relationship between individual genotypes and traits is defined by a network connecting loci to traits through a set of hidden internal nodes (Fig \ref{fig:network}).
Values for loci are randomly drawn from a standard normal distribution, \(\mathcal{N}\left(0, 1\right)\).
Links between loci, internal nodes, and traits, can take any real value and are represented by black arrows in Fig \ref{fig:network}.
Traits can take any real value, and are calculated as the summed effects of all preceding nodes (i.e., the blue squares immediately to the left of the traits in Fig \ref{fig:network}).
Mathematically, loci are represented by a row vector of length \(L\).
Effects of loci on the first layer of internal nodes (black arrows emanating from loci in Fig \ref{fig:network}) are represented by an \(L \times T\) matrix, and transitions between internal nodes, and between the last set of internal nodes and the final traits, are represented by \(T \times T\) matrices.
For the example in Fig \ref{fig:network},

\[
\begin{pmatrix}
  0.1, & -0.1, & 0.2 \\
\end{pmatrix} 
\begin{pmatrix}
  0.4, &  0.1 \\
 -1.2, & -0.6 \\
  0.2, &  2.2 \\
\end{pmatrix}
\begin{pmatrix}
   1.3, & -0.5 \\
  -0.1  &  0.0 \\
\end{pmatrix}
\begin{pmatrix}
   2.2, &  0.9 \\
   1.6  &  0.8 \\
\end{pmatrix} = 
\begin{pmatrix}
  0.2998, & 0.1081 \\
\end{pmatrix}.
\]

Values mapping loci to traits become part of an individual's genome, so the genome for the individual represented by Fig \ref{fig:network} is stored in the model as shown below:

\begin{verbatim}
0.1, -0.1, -0.2, 0.4, 0.1, -1.2, -0.6, 0.2, 2.2, 1.3, -0.5, -0.1, 0.0, 2.2, 0.9, 1.6, 0.8
\end{verbatim}

Individuals with different loci can therefore have different covarying traits that are constrained by the network structure encoded in each genome.
Individuals can be haploid (as in Fig \ref{fig:network}) or diploid (in which case, allele values are summed at homologous loci).

An evolutionary algorithm is used to find appropriate values that produce covarying traits from loci (see Supporting Information 1 for details).
Evolutionary algorithms are heuristic tools that can simulate adaptive evolution to find solutions for a broad range of problems \citep{Hamblin2013, Duthie2018}.
In the resevol package, the \texttt{mine\_gmatrix} function runs an evolutionary algorithm and requires the argument \texttt{gmatrix}, which specifies the desired trait covariance matrix.
The function initialises a population of \texttt{npsize} separate, and potentially unique, networks (i.e., \texttt{npsize} copies of a network like the one shown in Fig \ref{fig:network}), and this population evolves until some maximum iteration (\texttt{max\_gen}) or minimum expected network stress (\texttt{term\_cri}) is met.
In a single iteration of the algorithm, values mutate and crossover occurs between networks (i.e., some of the \texttt{npsize} networks swap values with some probability).
Next, trait covariances produced for each network are estimated by initalising \texttt{indivs} individuals with loci sampled from a standard normal distribution.
Network stress is calculated as the logged mean squared deviation between estimated covariances and those in \texttt{gmatrix}.
Tournament selection \citep{Hamblin2013} is then used to determine the networks for the next iteration of the algorithm.
Networks with the lowest estimated stress have the highest fitness, so these networks are disproportionately represented in the next iteration.
Throughout the evolutionary algorithm, the lowest stress network is saved and returned upon network termination.
The robustness of this network's stress to sets of individuals with different loci values can be tested using the \texttt{stress\_test} function.

An example run of \texttt{mine\_gmatrix} with the same number of loci and internal nodes as in Fig \ref{fig:network} is shown below for traits that have an intended covariance of -0.4:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{trait\_covs  }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\AttributeTok{data =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.4}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.4}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{);}
\NormalTok{new\_network }\OtherTok{\textless{}{-}} \FunctionTok{mine\_gmatrix}\NormalTok{(}\AttributeTok{loci =} \DecValTok{3}\NormalTok{, }\AttributeTok{layers =} \DecValTok{2}\NormalTok{, }\AttributeTok{gmatrix =}\NormalTok{ trait\_covs, }
                            \AttributeTok{max\_gen =} \DecValTok{1000}\NormalTok{, }\AttributeTok{term\_cri =} \SpecialCharTok{{-}}\FloatTok{6.0}\NormalTok{, }\AttributeTok{prnt\_out =} \ConstantTok{FALSE}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

The code above found a genome that produced the following expected trait covariances:

\begin{verbatim}
##            [,1]       [,2]
## [1,]  1.0008181 -0.3925799
## [2,] -0.3925799  1.0271340
\end{verbatim}

The mean deviation between elements of the above matrix and the identity matrix provided by \texttt{trait\_covs} is \ensuremath{2.1176024\times 10^{-4}}.
Lower values of \texttt{term\_cri} and higher values of \texttt{max\_gen} will result in a lower stress, but this will require more computation time, especially if the number of traits is high.
Similarly, higher values of \texttt{indivs} will result in more accurate estimations of true stress, but this also requires more computation time.
Additional arguments to \texttt{mine\_gmatrix} can also be used to improve the performance of the evolutionary algorithm (see Supporting Information 1).

\hypertarget{simulating}{%
\subsection{Simulating landscape-level pesticide resistance}\label{simulating}}

The full output of \texttt{mine\_gmatrix} is passed to the \texttt{run\_farm\_sim} function, which initialises and simulates an evolving population of pests on a changing landscape for any natural number of time steps (\texttt{time\_steps}).
In this section, we explain the landscape, pest ecology, and evolving pest traits.

\hypertarget{landscape}{%
\subsubsection{Landscape}\label{landscape}}

Landscapes are spatially explicit and initialised in one of two ways.
First, a landscape can be built from the arguments \texttt{xdim}, \texttt{ydim}, and \texttt{farms}.
These arguments specify the cell dimensions and number of farms on the landscape.
Contiguous rectangular farms of roughly equal size are generated on the landscape using a splitline algorithm.
Second, a custom landscape can be input using the \texttt{terrain} argument, which takes a matrix with elements that include integers 1 to \texttt{farms}.
Each value defines a unique farm, but values do not need to be contiguous.
These `farms' could even model non-farmland (e.g., water, roads), if pesticides and crops on them are invisible to pests (see Supporting Information 2), or they could more broadly be interpreted as heterogenous landscape properties across an arbitrary scale \citep[e.g.,][]{Newman2023}.
This \texttt{terrain} customisation therefore allows for a high degree of landscape detail, and offers the potential for modelling real-world landscapes from raster images \citep[e.g.,][]{Millington2021}.
Edge effects are set using the \texttt{land\_edge} argument.
Edge options include \texttt{"leaky"} (pests disappear from the landscape), \texttt{"reflect"} (pests bounce off of the edge), \texttt{"sticky"} (pests stick to the edge), or \texttt{"torus"} (pests that move off of one edge return on the opposite side of the landscape).

Each farm can hold one pesticide and one crop type in any time step.
The \texttt{crop\_init} and \texttt{pesticide\_init} arguments initialise one of \texttt{crop\_number} crops and one of \texttt{pesticide\_number} pesticides for each farm, respectively (maximum of 10 each).
Initialisation can be random for each farm with equal probability, or it can be set using a vector of length \texttt{farms} in which vector elements define the initialised crop or pesticide number.
After initialisation, crops and pesticides rotate once every \texttt{crop\_rotation\_time} and \texttt{pesticide\_rotation\_time} time steps, respectively.
The arguments \texttt{crop\_rotation\_type} and \texttt{pesticide\_rotation\_type} specify how crops and pesticides are rotated, respectively.
Each of these rotation type arguments can take either an integer value from 1-3, or a matrix.
Integer values specify (1) no rotation, (2) random transition from one type to another, or (3) cycling through each available crop or pesticide in numeric order.
Square matrices can be used to define the probability that a given crop or pesticide in row \(i\) transitions to that in column \(j\).
Hence, any possible Markov chain can be used to model transition between crop or pesticide types on farms, potentially integrating real crop use or pesticide use patterns \citep{Zhang2020}.
Upon rotation, crop and pesticide values are reset on each farm.

Values for \texttt{crop\_per\_cell} and \texttt{pesticide\_per\_cell} determine the quantity of crops and pesticides initialised per cell upon crop or pesticide rotation, respectively.
Between crop rotations, crop values can increase each time step by a proportion or increment \texttt{crop\_growth}, which depends on \texttt{crop\_growth\_type}.
These arguments can be used to model crop growth over a season.

\hypertarget{ecology}{%
\subsubsection{Pest ecology}\label{ecology}}

Individual pests can be modelled to have several reproductive systems and life histories.
Pest reproductive system can be specified using the \texttt{repro} argument, which accepts \texttt{"asexual"} (haploid), \texttt{"sexual"} (monoecious), and \texttt{"biparental"} (dioecious).
For \texttt{"sexual"} pests, the \texttt{selfing} argument specifies if self-fertilisation is (\texttt{TRUE}) or is not (\texttt{FALSE}) allowed.
At the start of a simulation, pests are initialised in a random location.
Initialised pests are of age zero if \texttt{rand\_age\ =\ FALSE} or a random age from zero to \texttt{max\_age} if \texttt{rand\_age\ =\ TRUE}.
Following initialisation, a single time step proceeds with landscape change (see above), pest aging and metabolism, feeding, pesticide consumption, movement, reproduction, mortality, and immigration (Fig \ref{fig:flowchart}).
Feeding, pesticide consumption, movement, and reproduction all depend on pest age.
Pests feed and consume pesticide from ages \texttt{min\_age\_feed} to \texttt{max\_age\_feed}, move from ages \texttt{min\_age\_move} to \texttt{max\_age\_move}, and reproduce from ages \texttt{min\_age\_reproduce} to \texttt{max\_age\_reproduce} (all inclusive).
Food accumulated is lost during aging if \texttt{baseline\_metabolism\ \textgreater{}\ 0} and pest age is within \texttt{min\_age\_metabolism} and \texttt{max\_age\_metabolism}.
The option to set minimum and maximum ages for events makes it possible to model pests with much different life histories \citep[e.g.,][]{Sudo2018}.

\begin{figure}
\centering
\includegraphics{ms_files/figure-latex/flowchart-1.pdf}
\caption{\label{fig:flowchart}Overview of simulated events in the resevol R package. Note that metabolism, feeding, pesticide consumption, movement, and reproduction are all subject to a minimum and maximum pest age. Consequently, simulation order might not reflect the order of events from the perspective of a focal pest (e.g., pests might move from ages 1-2, but only feed from ages 2-4). Crops and pesticides are also not necessarily rotated in each time step (see Landscape). Statistics collected within a time step are printed to a CSV file.}
\end{figure}

In each time step, pests feed in a random order, consuming the crop on their landscape cell. Each pest consumes an amount of crop as specified by the \texttt{food\_consume} argument, which takes a vector with as many elements as their are crops (i.e., if \texttt{crop\_number\ =\ 2}, then \texttt{food\_consume} has two elements, the first and second defining consumption of crops 1 and 2, respectively).
If crop amount on the landscape cell exceeds pest consumption ability, then pests consume their maximum amount, and this amount is removed from the landscape cell.
If crop amount is less than pest consumption ability, then pests consume whatever crop is left and crop amount is reduced to zero.
Pesticide consumption works identically to crop consumption, except that the amount of pesticide on a landscape cell is not decreased.
Hence, each pest can potentially feed and be affected by the pesticide of their focal landscape cell.
Pests simply consume an amount of pesticide as specified by the \texttt{pesticide\_consume} argument, which also takes a vector with as many elements as their are pesticides.
Pesticide consumption affects pest survival and reproduction using \texttt{pesticide\_tolerated\_surv} and \texttt{pesticide\_tolerated\_repr} arguments.

After interacting with their landscape cell, pests can move.
Each pest visits a number of cells during movement, as is specified by the parameter \texttt{movement\_bouts}.
Individual movement bouts occur in a random order across pests.
During a movement bout, a pest can travel to any cell within a value defined by \texttt{movement\_distance} from their current location, which could include their current location (i.e., moving zero distance).
Upon arrival to a cell, a pest can feed if they are of an appropriate feeding age and \texttt{feed\_while\_moving\ =\ TRUE}.
The pest also consumes pesticide if they are of the appropriate age and \texttt{pesticide\_while\_moving\ =\ TRUE}.
Having pests feed and consume pesticide in a random order while moving among landscape cells can model a population competing for food and encountering pesticides on a shorter time scale than an individual time step.

After all pests finish moving, pests reproduce.
Offspring production is possible for asexual, monoecious, or female pests.
Pest expected offspring number is defined by a fixed parameter if \texttt{reproduction\_type\ =\ "lambda"}, or is calculated from the amount of food consumed if \texttt{reproduction\_type\ =\ "food\_based"}.
The former requires specifying \texttt{lambda\_value}, which becomes the rate parameter for sampling offspring number from a Poisson distribution.
The latter requires specifying a real value for \texttt{food\_needed\_repr}, which is the amount of food needed to produce one offspring.
For food-based reproduction, the total amount of food consumed is divided by \texttt{food\_needed\_repr}, then floored to determine offspring number.
Sexual reproduction requires a mate of reproductive age that is either monoecious or male, and within range of the reproducing focal pest (potential including the focal pest, if \texttt{selfing\ =\ TRUE}).
A potential mate is within range if it is within an integer number of cells from the focal pest, as defined by \texttt{mating\_distance} (e.g., if \texttt{mating\_distance\ =\ 0}, then mates must share a landscape cell).
All available potential mates sire offspring with equal probability, and reproducing pests are assumed to mate multiply (i.e., paternity is a fair raffle for all offspring).
If a carrying capacity at birth is set (\texttt{K\_on\_birth\ \textgreater{}\ 0}) and total offspring number in the population exceeds this capacity, then offspring are removed at random until they are within carrying capacity.
A real value \texttt{immigration\_rate} specifies the rate parameter for Poisson random sampling of the number of immigrants added to the population at the end of a time step.
Immigrants are initialised in the same way as pests are at the start of the simulation.
Hence, any spatial structure or evolution that occurs during the simulation does not affect immigrant locations, genomes, or traits.

\hypertarget{evolution}{%
\subsubsection{Pest evolution}\label{evolution}}

Pest genomes evolve in a complex and highly mechanistic way.
Offspring inherit genome values from their parent(s) with the possibility for mutation and recombination; offspring traits are then calculated from their newly initialised genomes.
For asexually and sexually reproducing pests, genomes are haploid and diploid, respectively.
Asexually reproducing pests receive the full genomes of their parent, while sexually reproducing pests receive half of their alleles from each parent.
Each diploid parent contributes one half of their genome, effectively modelling a genome with a single chromosome.
Crossover occurs at each position of the genome with a probability of \texttt{crossover\_pr}.
When a crossover event occurs, alleles are swapped between the two chromosomes, so complete recombination is also possible if \texttt{crossover\_pr\ =\ 0.5}.
For both haploids and diploids, each genome value then mutates independently with a probability of \texttt{mutation\_pr}, which can be set to any real number from 0-1.
If a genome value mutates, then a new value is randomly sampled from a standard normal distribution.
If \texttt{mutation\_type\ =\ 0}, then this new value replaces the old value, and if \texttt{mutation\_type\ =\ 1}, then the new value is added to the old value.
After mutation, genome values are used to calculate trait values.

Evolution of the genetic architecture linking loci to traits can be constrained by disabling mutation in genome values linking loci, internal nodes, and traits (i.e., `network values' represented by arrows in Fig \ref{fig:network}).
While mutation at loci (green circles in Fig \ref{fig:network}) is always possible as long as \texttt{mutation\_pr\ \textgreater{}\ 0}, the number of intermediary layers for which network values can mutate is constrained by \texttt{net\_mu\_layers}.
If \texttt{net\_mu\_layers\ =\ 0}, then no network values can mutate, but higher integer values cause mutation to occur at network value layers from loci to traits (if \texttt{net\_mu\_dir\ =\ 1}) or traits to loci (if \texttt{net\_mu\_dir\ =\ 0}).
For example, if \texttt{net\_mu\_layers\ =\ 2} and \texttt{net\_mu\_dir\ =\ 1}, then the network values linking loci to the first internal node, and the first internal node to the second, can mutate (i.e., first two columns of arrows in \ref{fig:network}, but not those linking the second internal node to traits).
This allows pest traits to evolve with varying degrees of constraint on the covariance between traits.
Low \texttt{net\_mu\_layers} values model strong genetic constraints, while high values model high evolvability of trait covariances.

Finally, evolving and covarying traits can be used in place of fixed parameters described in pest ecology.
This is done by substituting \texttt{"Tj"} as an argument input in place of a numeric value, where \texttt{j} represents the trait number.
For example, the argument \texttt{move\_distance\ =\ "T1"} will make Trait 1 the movement distance for individuals.
The argument \texttt{food\_consume\ =\ c("T2",\ "T3")} will set Traits 2 and 3 to define the amount of food of types 1 and 2 that can be consumed by a pest, respectively.
Up to 10 of the following parameters can be replaced with evolving traits: \texttt{move\_distance}, \texttt{food\_needed\_surv}, \texttt{pesticide\_tolerated\_surv}, \texttt{food\_needed\_repr}, \texttt{pesticide\_tolerated\_repr}, \texttt{mating\_distance}, \texttt{lambda\_value}, \texttt{movement\_bouts}, \texttt{metabolism}, \texttt{food\_consume}, and \texttt{pesticide\_consume}.
Mean values of traits can be set using the argument \texttt{trait\_means}, which accepts a vector of the same length as the number of evolving traits such that indices correspond to trait numbers.
The resevol package can thereby simulate agricultural pests with complex and co-evolving traits, and potentially evolving trait covariances, under a range of possible pest life histories.

\hypertarget{output}{%
\subsection{Simulation output}\label{output}}

Simulation output is typically large, so output is printed in two CSV files, both of which are created in the working directory.
The first file ``population\_data.csv'' prints population level data over time, including population size, mean age, sex ratio, mean food and pesticide consumed of each type, mortality rate, and mean trait values.
The second file ``individuals.csv'' prints all information, including full genomes and traits (columns), for every individual (rows) in the population.
The printing of individual level data is disabled by default.
It can be turned on for all time steps by setting \texttt{print\_inds\ =\ TRUE}, but this should be done with caution because it can create extremely large files.
Instead, individual level data can be printed for only the final time step by setting \texttt{print\_last\ =\ TRUE}.
Output produced by \texttt{run\_farm\_sim} is a list of two elements, which includes a vector of parameter values used in the simulation and the final state of the landscape as an array.

\hypertarget{simulation}{%
\section{Results}\label{simulation}}

In resevol v0.3, the \texttt{run\_farm\_sim} function includes 68 arguments, which specify a wide range of possible simulation conditions affecting landscape and pest characteristics.
These arguments are explained in the package documentation, and in Supporting Information 2, which demonstrates an advanced case study with a custom landscape and complex pest genomes and life history.
Here we focus on a simple simulation with asexually reproducing pests that have three loci and two traits (Fig \ref{fig:network}).
We use the the genome generated in \texttt{new\_network} from \protect\hyperlink{mine_gmatrix}{Section 2}, in which traits 1 and 2 have variances of 1.0008181 and 1.027134, respectively, with a covariance of -0.3925799.

Traits 1 and 2 will define the realised rate of uptake of the two separate pesticides, so we model a system in which there is a potential trade-off for pesticide susceptibility.
We use a simple \(64 \times 64\) cell landscape with nine farms.
Each farm grows the same crop and uses one of two randomly intialised pesticides, which are rotated every 16 time steps.
Hence, we can conceptualise 16 time steps as a single growing season.

In our example, each cell produces four crop units, all of which can potentially be consumed.
Pests consume up to one unit of crop on their landscape cell per time step.
Pest survival and reproduction is food-based, and pests need to consume one unit of crop by age two to survive and reproduce.
Pests initialised at the start of the simulation are randomly assigned an age from 0-4 with equal probability.
Pests have a maximum age of four, and they feed in ages 0-2, move up to two cells in ages 3-4, and reproduce in age four.
Pests can uptake (i.e., `consume') pesticides in ages 0-2, and if they consume any pesticide, then they will die.
In each time step, a mean of 10 immigrants arrive.
We simulate 160 time steps (10 growing seasons) using the function below:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim }\OtherTok{\textless{}{-}} \FunctionTok{run\_farm\_sim}\NormalTok{(}\AttributeTok{mine\_output =}\NormalTok{ new\_network, }\AttributeTok{repro =} \StringTok{"asexual"}\NormalTok{, }
                    \AttributeTok{pesticide\_number =} \DecValTok{2}\NormalTok{, }\AttributeTok{pesticide\_init =} \StringTok{"random"}\NormalTok{, }
                    \AttributeTok{pesticide\_consume =} \FunctionTok{c}\NormalTok{(}\StringTok{"T1"}\NormalTok{, }\StringTok{"T2"}\NormalTok{), }\AttributeTok{farms =} \DecValTok{9}\NormalTok{,}
                    \AttributeTok{pesticide\_rotation\_time =} \DecValTok{16}\NormalTok{, }\AttributeTok{pesticide\_rotation\_type =} \DecValTok{3}\NormalTok{,}
                    \AttributeTok{pesticide\_tolerated\_surv =} \DecValTok{0}\NormalTok{, }\AttributeTok{pesticide\_per\_cell =} \DecValTok{1}\NormalTok{,}
                    \AttributeTok{crop\_rotation\_time =} \DecValTok{16}\NormalTok{, }\AttributeTok{crop\_number =} \DecValTok{1}\NormalTok{, }\AttributeTok{crop\_per\_cell =} \DecValTok{4}\NormalTok{, }
                    \AttributeTok{food\_consume =} \DecValTok{1}\NormalTok{, }\AttributeTok{reproduction\_type =} \StringTok{"food\_based"}\NormalTok{, }
                    \AttributeTok{food\_needed\_surv =} \DecValTok{1}\NormalTok{, }\AttributeTok{food\_needed\_repr =} \DecValTok{1}\NormalTok{, }\AttributeTok{max\_age =} \DecValTok{4}\NormalTok{, }
                    \AttributeTok{min\_age\_feed =} \DecValTok{0}\NormalTok{, }\AttributeTok{max\_age\_feed =} \DecValTok{2}\NormalTok{, }\AttributeTok{min\_age\_move =} \DecValTok{3}\NormalTok{, }
                    \AttributeTok{max\_age\_move =} \DecValTok{4}\NormalTok{, }\AttributeTok{min\_age\_reproduce =} \DecValTok{4}\NormalTok{, }\AttributeTok{print\_gens =} \ConstantTok{FALSE}\NormalTok{,}
                    \AttributeTok{max\_age\_reproduce =} \DecValTok{4}\NormalTok{, }\AttributeTok{age\_pesticide\_threshold =} \DecValTok{2}\NormalTok{, }
                    \AttributeTok{rand\_age =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{move\_distance =} \DecValTok{2}\NormalTok{, }\AttributeTok{immigration\_rate =} \DecValTok{10}\NormalTok{, }
                    \AttributeTok{time\_steps =} \DecValTok{160}\NormalTok{, }\AttributeTok{print\_last =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{xdim =} \DecValTok{64}\NormalTok{, }\AttributeTok{ydim =} \DecValTok{64}\NormalTok{,}
                    \AttributeTok{trait\_means =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.1}\NormalTok{), }\AttributeTok{land\_edge =} \StringTok{"torus"}\NormalTok{);}
\end{Highlighting}
\end{Shaded}

Any arguments to \texttt{run\_farm\_sim} not included above are set to default values.
\protect\hyperlink{output}{Output files} can be used to plot ecological and evolutionary dynamics of pests.
Fig \ref{fig:overtime}a shows the pest population change both across and within seasons.
Due to the specific parameter values chosen, clear patterns reflecting pest cohorts emerge.
At the start of a season when the most crop is available, pests eat and abundance increases.
As less crop remains in a season, pest abundance decreases.
Mean food consumed varies over the course of a season caused by the varying frequency of pests in different life history stages (Fig \ref{fig:overtime}c).
In the first 50 time steps, there is some consumption of pesticides 1 and 2 (Fig \ref{fig:overtime}b), but both traits rapidly evolve to negative values making both pesticides ineffective (Fig \ref{fig:overtime}d).
In this case, the trade-off in pesticide consumption is not strong enough to maintain susceptibility to either pesticide in the population.
Fig \ref{fig:landscape} shows the location of pests on the landscape in the last time of the simulation (left panel), and how different pesticides are currently being applied on the landscape (right panel).
Because the number of crops and pesticides, the number and nature of traits, and the size of pest genomes all vary depending on simulation parameters, no plotting functions are introduced in the resevol package.
Instead, methods and code for producing plots such as those in Fig \ref{fig:overtime} and \ref{fig:landscape} are explained in Supporting Information 2.

\begin{figure}
\centering
\includegraphics{ms_files/figure-latex/overtime-1.pdf}
\caption{\label{fig:overtime}Agricultural pest ecological and evolutionary dynamics over 160 time steps from an individual-based simulation using the resevol R package. Panels show (a) pesticide abundance change, (b) mean realised amount of pesticides 1 and 2 uptaken per pest, (c) mean food consumed per pest, and (d) mean value of evolving traits 1 and 2 underlying pest uptake over time. Note that only pests with positive values for Traits 1 or 2 can uptake Pesticide 1 or 2, respectively. Pests with negative trait values will be unaffected by corresponding pesticides (i.e., pesticide consumption is a threshold trait), hence the difference between realised pesticide consumption (b) and the traits underlying it (d). White and grey vertical stripes indicate seasons of a single crop and pesticide application.}
\end{figure}

\begin{figure}
\centering
\includegraphics{ms_files/figure-latex/landscape-1.pdf}
\caption{\label{fig:landscape}Locations of pests (black) across a landscape that includes nine farms (coloured blocks) in the last time step of a simulation using the resevol R package (left panel). The right panel shows which farms apply pesticide 1 (dark grey) and 2 (light grey).}
\end{figure}

\hypertarget{conclusions}{%
\section{Availability and Future Directions}\label{conclusions}}

Insecticide resistance to pesticides is a widespread problem that affects global food security \citep{Tabashnik2014, Bradshaw2016, Lykogianni2021}.
Many models have been developed to investigate the evolution of resistance under different ecological and evolutionary conditions \citep[e.g.,][]{Curtis1985, Mani1985, Ives2002, Liang2013, Liang2018, Haridas2018, South2018, Sudo2018, Saikai2021}.
The resevol R package makes it possible to rapidly develop and simulate myriad individual-based models of resistance evolution.
It also introduces a novel approach to modelling complex pest genetic architecture, using an evolutionary algorithm to generate haploid or diploid loci that map to pest traits with pre-specified covariances (Fig \ref{fig:network}; Supporting Information 1).
Agricultural landscapes and pest life histories are highly customisable, allowing targetted models that can simulate specific real-world case studies (Supporting Information 2).
The breadth of possible models that can be simulated with resevol also makes it a useful tool for developing theory on pest management, and even more generally on the evolution and ecology of individuals with complex traits on a heterogeneous landscape.

The resevol R package can be downloaded from CRAN (\url{https://cran.r-project.org/package=resevol}) or GitHub (\url{https://bradduthie.github.io/resevol/}).
The package is open source under GNU Public License.

\hypertarget{contributions}{%
\section{Authors contributions}\label{contributions}}

All authors contributed to planning software development and writing.
ABD wrote and maintains package code.
CRM contributed code for data visualisation.

\hypertarget{financial}{%
\section{Financial Disclosure statement}\label{financial}}

This software was developed as part of the project for Enhancing Diversity to Overcome Resistance Evolution (ENDORSE) led by Luc Bussière, Ricardo Polanczyk, and Matthew Tinsley (Co-Investigators: Nils Bunnefeld, Yelitza Colmenarez, Natália Corniani, Renata de Lima, Brad Duthie, Steve Edgington, Leonardo Fraceto, Belinda Luke, and Rosie Mangan).
The ENDORSE project is a joint Newton funded international partnership between the Biotechnology and Biological Sciences Research Council (BBSRC) in the UK and the São Paulo Research Foundation (FAPESP) in Brazil under BBSRC award reference BB/S018956/1 and FAPESP award reference 2018/21089-3.
ENDORSE is a partnership among Universidade Estadual Paulista (UNESP), the University of Stirling (UoS), and the Centre for Agricultural and Biosciences International (CABI).
The funders had no role in study design, data collection and analysis, decision to publish, or preparation of the manuscript.

\hypertarget{competing}{%
\section{Competing interests}\label{competing}}

The authors have declared that no competing interests exist.

\hypertarget{references}{%
\section{References}\label{references}}

\hypertarget{SI}{%
\section{Supporting information}\label{SI}}

S1 Text. The evolutionary algorithm of the resevol R package, including key data structures used, a general overview of the evolutionary algorithm, and details concerning haploid and diploid individuals. (PDF)

S2 Text. Advanced techniques for using the resevol R package, including initialising pest genomes and running simulations. (PDF)

  \bibliography{resevol.bib}

\end{document}
