---
title: "Duthie Work Package"
author: "Brad Duthie"
date: "17 September 2018"
output:
  word_document:
    reference_docx: docx_template.docx
  pdf_document: default
  html_document: default
bibliography: references.bib
link-citations: yes
linkcolor: blue
csl: science.csl
biblio-style: apalike
---


Duthie Suitability
================================================================================

Brad Duthie is a theoretical biologist with a proven track record in modelling complex ecological and evolutionary systems (1-2). His previous research has included modelling evolutionary dynamics of inbreeding behaviour given complex genetic architectures and population pedigrees (3-5), ecological interactions among species on spatially explicit landscapes (6), and software development for modelling population management (7).

(1) Duthie, A. B., Abbott, K. C., & Nason, J. D. (2014). Trade-offs and coexistence: A lottery model applied to fig wasp communities. American Naturalist, 183(6), 826–841. https://doi.org/10.1086/675897

(2) Duthie, A. B., Lee, A. M., & Reid, J. M. (2016). Inbreeding parents should invest more resources in fewer offspring. Proceedings of The Royal Society B, 20161845. https://doi.org/10.1098/rspb.2016.184

(3) Duthie, A. B., Bocedi, G., & Reid, J. M. (2016). When does female multiple mating evolve to adjust inbreeding? Effects of inbreeding depression, direct costs, mating constraints, and polyandry as a threshold trait. Evolution, 70(9), 1927–1943. https://doi.org/10.1111/evo.13005

(4) Duthie, A. B., & Reid, J. M. (2016). Evolution of inbreeding avoidance and inbreeding preference through mate choice among interacting relatives. American Naturalist, 188(6), 000–000. https://doi.org/10.1086/688919

(5) Duthie, A. B., Bocedi, G., Germain, R. R., & Reid, J. M. (2018). Evolution of pre-copulatory and post-copulatory strategies of inbreeding avoidance and associated polyandry. Journal of Evolutionary Biology. https://doi.org/10.1111/jeb.13189

(6) Duthie, A. B., & Falcy, M. R. (2013). The influence of habitat autocorrelation on plants and their seed-eating pollinators. Ecological Modelling, 251, 260–270. https://doi.org/10.1016/j.ecolmodel.2012.12.019

(7) Duthie, A. B., Cusack, J. J., Jones, I. L., Nilsen, E. B., Pozo, R. A., Rakotonarivo, O. S., … Bunnefeld, N. (2018). GMSE: an R package for generalised management strategy evaluation. Methods in Ecology and Evolution. https://doi.org/10.1101/221432


Duthie Work Package
================================================================================

To demonstrate how rotating biopesticide strains and crop species at the local scale can ultimately overcome pest resistance in the long-term at the landscape scale, we will simulate the full social-ecological system using an individual-based model (IBM). IBMs allow for interactions among discrete individuals (*H. armigera* pests) on a spatially-explicit landscape where key landscape properties (biopesticide application, crop species) vary locally [@Bocedi2014a; @Duthie2018]. Individuals can have complex genetic architectures that underly relevant quantitative traits such as bipesticide resistance, feeding efficiency, and dispersal behaviour [@Grimm2005; @DeAngelis2005; @Duthie2015]. Landscapes can be equally complex, allowing individual traits to interact with the unique set of landscape properties that occur on an landscape cell [@Duthie2013; @Peer2013; @Aben2014]. By parameterising pest genetic architecture with real estimates of dispersal and measures of genetic associations from Phase I/1a, then simulating different biopesticide application and crop choice regimes on landscape cells, we can use IBMs to model the evolution of bipesticide resistance *in silico* [@Stratonovitch2014].

A prototype model of the evolution of *H. armigera* biopesticide resistance has already been developed using a simplified genetic achitecture and landscape. Simulations from this prototype demonstrate that biopesticide and crop rotatation can overcome biopesticide resistance in principle (see http://r.rosemckeon.co.uk/helicoverpa/), but these results have yet to be demonstrated with a suitably realistic genetic architecture and landscape properties. This work package will include the required realism in an expanded model to simulate the long-term evolution of *H. armigera* resistance. The model will be built as an open-source R package, written in R and C, and made accessible to all on GitHub. The R package will be externally evaluated by the rOpenSci community, which will include review by two independent experts who will comment on code usability and quality.

<div id="refs"></div>


Duthie Costings
================================================================================

In theory, I believe that I have all the resources I need to do this -- basically a good computer and time to code. If there is a way to buy out my time for programming after 31 OCT 2020, it would be helpful. If there is room for it in the budget (though it's not really critical), it might be useful to include some money (ca 500 GBP) for cluster time and (maybe ca 250 GBP) for server time, if we're going to be releasing a shiny output online. 

As mentioned in a previous meeting, I don't think I need postdoc time -- it would be great to collaboratively code with someone on this, but for it to be a net benefit, I think, in terms of efficiency in getting things done, we'd want to hire someone with biological modelling experience and programming experience in C or C++ (I can ask around -- know at least one good coder that might be looking for a job). I'm totally on board if it can be done, but we'd probably want the person to be on salary for at least a year? (or, if less, perhaps a remote worker could do -- collaboration via GitHub means that a potential postdoc wouldn't need to be physically in Stirling or Brazil). 

