library("helicoverpa");
set.seed(Sys.time());
mg  <- readRDS("mg.rds");
sim <- run_farm_sim(mine_output              = mg,
                    N                        = 1000,
                    neutral_loci             = 1000,
                    xdim                     = 100,
                    ydim                     = 100,
                    repro                    = "asexual",
                    max_age                  = 4,
                    selfing                  = FALSE,
                    food_consume             = c("T1", "T2"),
                    pesticide_consume        = c("T3", "T4"),
                    food_needed_surv         = 2,
                    food_needed_repr         = 2,
                    reproduction_type        = "food_based",
                    pesticide_tolerated_surv = 1,
                    pesticide_rotation_type  = 2,
                    crop_rotation_type       = 1,
                    min_age_reproduce        = 4,
                    max_age_feed             = 2,
                    lambda_value             = 1.5,
                    farms                    = 24,
                    time_steps               = 800,
                    mutation_pr              = 0.001,
                    crossover_pr             = 0.1,
                    net_mu_layers            = 0,
                    crop_rotation_time       = 12,
                    pesticide_rotation_time  = 12,
                    crop_per_cell            = 2,
                    pesticide_per_cell       = 1,
                    crop_number              = 2,
                    pesticide_number         = 2,
                    print_inds               = FALSE, # Careful with this one
                    K_on_birth               = 10000,
                    min_age_move             = 3,
                    age_food_threshold       = 2,
                    min_age_feed             = 1,
                    pesticide_start          = 200,
                    print_last               = TRUE,
                    mating_distance          = 2,
                    immigration_rate         = 40
);
